before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - tap:
      owner: joaofnds
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: joaofnds
      email: joaofnds@joaofnds.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    url_template: "https://github.com/joaofnds/astro/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/joaofnds/astro"
    description: "a habit tracker for your terminal with a GitHub style activity graph"
    license: "MIT"

aurs:
  - name: astro-bin
    homepage: "https://astro.joaofnds.com/"
    description: "A habit tracker for your terminal with a GitHub style activity graph"
    license: "MIT"
    maintainers: ["João Fernandes <joaofnds@joaofnds.com>"]
    contributors: ["João Fernandes <joaofnds@joaofnds.com>"]
    conflicts: ["astro"]

    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/astro-bin.git"
    commit_author:
      name: joaofnds
      email: joaofnds@joaofnds.com

    package: |
      install -Dm755 "./astro" "${pkgdir}/usr/bin/astro"
